### ISSUE TITLE
DOGE electrum crashed with assert self.binary_length >= end, restart not possible

### ISSUE THREAD

**Issue by cipig** [spesmilo/electrumx#99] opened 2021-02-17 14:56 UTC
```
ERROR:electrumx:ElectrumX server terminated abnormally
Traceback (most recent call last):
  File "/usr/local/bin/electrumx_server", line 35, in main
    asyncio.run(controller.run())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/server_base.py", line 125, in run
    await server_task
  File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/server_base.py", line 98, in serve
    await self.serve(shutdown_event)
  File "/usr/local/lib/python3.7/dist-packages/electrumx/server/controller.py", line 134, in serve
    await group.spawn(wait_for_catchup())
  File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 681, in fetch_and_process_blocks
    await group.spawn(self._process_prefetched_blocks())
  File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 642, in _process_prefetched_blocks
    await self.check_and_advance_blocks(blocks)
  File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 212, in check_and_advance_blocks
    for n, raw_block in enumerate(raw_blocks)]
  File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 212, in <listcomp>
    for n, raw_block in enumerate(raw_blocks)]
  File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/coins.py", line 247, in block
    txs = cls.DESERIALIZER(raw_block, start=len(header)).read_tx_block()
  File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 152, in read_tx_block
    return [read() for _ in range(self._read_varint())]
  File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 152, in <listcomp>
    return [read() for _ in range(self._read_varint())]
  File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 142, in read_tx_and_hash
    return self.read_tx(), self.TX_HASH_FN(self.binary[start:self.cursor])
  File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 130, in read_tx
    self._read_inputs(),    # inputs
  File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 156, in _read_inputs
    return [read_input() for i in range(self._read_varint())]
  File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 156, in <listcomp>
    return [read_input() for i in range(self._read_varint())]
  File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 162, in _read_input
    self._read_varbytes(),   # script
  File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 188, in _read_varbytes
    return self._read_nbytes(self._read_varint())
  File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 184, in _read_nbytes
    assert self.binary_length >= end
AssertionError
```

**Comment by APaddy** [comment] 2021-02-17 16:03
Same here.  Tried different electrumx versions, all exhibit the same exact behavior.

2021-02-17 15:58:25,805:INFO:Prefetcher:catching up to daemon height 3,611,765 (73 blocks behind) 
2021-02-17 15:58:25,824:INFO:BlockProcessor:flushing to DB for a clean shutdown... 
2021-02-17 15:58:25,825:INFO:SessionManager:closing down RPC listening servers 
ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /dogxserver/electrumx/electrumx/server/controller.py:81> exception=AssertionError()> 
Traceback (most recent call last): 
  File "/usr/local/lib/python3.6/dist-packages/aiorpcx/util.py", line 119, in check_task 
    task.result() 
  File "/dogxserver/electrumx/electrumx/server/controller.py", line 134, in serve 
    await group.spawn(wait_for_catchup()) 
  File "/usr/local/lib/python3.6/dist-packages/aiorpcx/curio.py", line 240, in __aexit__ 
    await self.join() 
  File "/usr/local/lib/python3.6/dist-packages/aiorpcx/curio.py", line 207, in join 
    raise task.exception() 
  File "/dogxserver/electrumx/electrumx/server/block_processor.py", line 669, in fetch_and_process_blocks 
    await group.spawn(self._process_prefetched_blocks()) 
  File "/usr/local/lib/python3.6/dist-packages/aiorpcx/curio.py", line 240, in __aexit__ 
    await self.join() 
  File "/usr/local/lib/python3.6/dist-packages/aiorpcx/curio.py", line 207, in join 
    raise task.exception() 
  File "/dogxserver/electrumx/electrumx/server/block_processor.py", line 630, in _process_prefetched_blocks 
    await self.check_and_advance_blocks(blocks) 
  File "/dogxserver/electrumx/electrumx/server/block_processor.py", line 201, in check_and_advance_blocks 
    for n, raw_block in enumerate(raw_blocks)] 
  File "/dogxserver/electrumx/electrumx/server/block_processor.py", line 201, in <listcomp> 
    for n, raw_block in enumerate(raw_blocks)] 
  File "/dogxserver/electrumx/electrumx/lib/coins.py", line 249, in block 
    txs = cls.DESERIALIZER(raw_block, start=len(header)).read_tx_block() 
  File "/dogxserver/electrumx/electrumx/lib/tx.py", line 136, in read_tx_block 
    return [read() for _ in range(self._read_varint())] 
  File "/dogxserver/electrumx/electrumx/lib/tx.py", line 136, in <listcomp> 
    return [read() for _ in range(self._read_varint())] 
  File "/dogxserver/electrumx/electrumx/lib/tx.py", line 126, in read_tx_and_hash 
    return self.read_tx(), self.TX_HASH_FN(self.binary[start:self.cursor]) 
  File "/dogxserver/electrumx/electrumx/lib/tx.py", line 114, in read_tx 
    self._read_inputs(),    # inputs 
  File "/dogxserver/electrumx/electrumx/lib/tx.py", line 140, in _read_inputs 
    return [read_input() for i in range(self._read_varint())] 
  File "/dogxserver/electrumx/electrumx/lib/tx.py", line 140, in <listcomp> 
    return [read_input() for i in range(self._read_varint())] 
  File "/dogxserver/electrumx/electrumx/lib/tx.py", line 146, in _read_input 
    self._read_varbytes(),   # script 
  File "/dogxserver/electrumx/electrumx/lib/tx.py", line 172, in _read_varbytes 
    return self._read_nbytes(self._read_varint()) 
  File "/dogxserver/electrumx/electrumx/lib/tx.py", line 168, in _read_nbytes 
    assert self.binary_length >= end 
AssertionError

**Comment by cipig** [comment] 2021-02-17 16:05
i am about to rebuild the entire DB on one of the nodes... will see if that helps...

**Comment by APaddy** [comment] 2021-02-17 16:07
Already doing it, let's see who will finish first.  Tbh I am not very optimistic about its results, because it seems to be crashing on a specific block, and it seems to be a problem of the deserializer.  The offending block is somewhere after 3,611,765

**Comment by cipig** [comment] 2021-02-17 16:54
it didn't help, electrumx is crashing during DB rebuild
```
Feb 17 16:47:29 electrum3 electrumx_server[3659377]: INFO:BlockProcessor:our height: 3,607,772 daemon: 3,611,818 UTXOs 959MB hist 140MB
Feb 17 16:47:36 electrum3 electrumx_server[3659377]: INFO:Prefetcher:cancelled; prefetcher stopping
Feb 17 16:47:36 electrum3 electrumx_server[3659377]: INFO:SessionManager:closing down server for rpc://localhost:8060
Feb 17 16:47:36 electrum3 electrumx_server[3659377]: INFO:Controller:shutting down
Feb 17 16:47:36 electrum3 electrumx_server[3659377]: INFO:Controller:shutdown complete
Feb 17 16:47:36 electrum3 electrumx_server[3659377]: ERROR:electrumx:ElectrumX server terminated abnormally
Feb 17 16:47:36 electrum3 electrumx_server[3659377]: Traceback (most recent call last):
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/bin/electrumx_server", line 35, in main
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     asyncio.run(controller.run())
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     return loop.run_until_complete(main)
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/server_base.py", line 125, in run
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     await server_task
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/server_base.py", line 98, in serve
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     await self.serve(shutdown_event)
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/controller.py", line 134, in serve
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     await group.spawn(wait_for_catchup())
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     await self.join()
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 211, in join
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     raise task.exception()
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 681, in fetch_and_process_blocks
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     await group.spawn(self._process_prefetched_blocks())
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     await self.join()
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 211, in join
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     raise task.exception()
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 642, in _process_prefetched_blocks
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     await self.check_and_advance_blocks(blocks)
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 212, in check_and_advance_blocks
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     for n, raw_block in enumerate(raw_blocks)]
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 212, in <listcomp>
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     for n, raw_block in enumerate(raw_blocks)]
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/coins.py", line 247, in block
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     txs = cls.DESERIALIZER(raw_block, start=len(header)).read_tx_block()
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 152, in read_tx_block
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     return [read() for _ in range(self._read_varint())]
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 152, in <listcomp>
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     return [read() for _ in range(self._read_varint())]
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 142, in read_tx_and_hash
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     return self.read_tx(), self.TX_HASH_FN(self.binary[start:self.cursor])
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 130, in read_tx
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     self._read_inputs(),    # inputs
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 156, in _read_inputs
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     return [read_input() for i in range(self._read_varint())]
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 156, in <listcomp>
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     return [read_input() for i in range(self._read_varint())]
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 162, in _read_input
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     self._read_varbytes(),   # script
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 188, in _read_varbytes
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     return self._read_nbytes(self._read_varint())
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 184, in _read_nbytes
Feb 17 16:47:36 electrum3 electrumx_server[3659377]:     assert self.binary_length >= end
Feb 17 16:47:36 electrum3 electrumx_server[3659377]: AssertionError
Feb 17 16:47:38 electrum3 systemd[1]: electrumx_DOGE.service: Succeeded.
```
looks like electrumx can't sync more than 3,6xx,xxx blocks or something

**Comment by ca333** [comment] 2021-02-17 22:24
plz add debug output in `_read_nbytes`  https://github.com/spesmilo/electrumx/blob/a6cb22aa3717d515e6853c5603b21d828d619d4e/electrumx/lib/tx.py#L181-L185
and `block`
https://github.com/spesmilo/electrumx/blob/a6cb22aa3717d515e6853c5603b21d828d619d4e/electrumx/lib/coins.py#L253-L257

will help investigation


>problem of the deserializer

yes likely 'malformed' tx for electrumx but technical valid tx or so

https://github.com/spesmilo/electrumx/blob/a6cb22aa3717d515e6853c5603b21d828d619d4e/electrumx/lib/tx.py#L151 ^ hint? - first lets find out specific block/tx for this problem

**Comment by APaddy** [comment] 2021-02-17 22:34
Solution provided by the very helpful Doge guys:
On lib/coins.py at the end of Doge Class definition "class Dogecoin(AuxPowMixin, Coin):" add the line 

DESERIALIZER = lib_tx.DeserializerAuxPowSegWit

**Comment by ca333** [comment] 2021-02-17 22:43
> Solution provided by the very helpful Doge guys:
> On lib/coins.py at the end of Doge Class definition "class Dogecoin(AuxPowMixin, Coin):" add the line
> 
> DESERIALIZER = lib_tx.DeserializerAuxPowSegWit

thanks - @cipig confirmed it fixed the problem

**Comment by ptyx11** [comment] 2021-02-17 23:14
You guys are awesome!

**Closed** 2021-02-17 23:18 UTC
