### ISSUE TITLE
server start normaly but after 4 or 5 mit it show this error. plaese provide correct answers.

### ISSUE THREAD

**Issue by thakurabu** [spesmilo/electrumx#260] opened 2024-04-30 06:18 UTC
ERROR:electrumx:ElectrumX server terminated abnormally
Traceback (most recent call last):
  File "/electrumx/electrumx_server", line 35, in main
    asyncio.run(controller.run())
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/electrumx/electrumx/lib/server_base.py", line 129, in run
    await server_task
  File "/electrumx/electrumx/lib/server_base.py", line 102, in serve
    await self.serve(shutdown_event)
  File "/electrumx/electrumx/server/controller.py", line 134, in serve
    await group.spawn(wait_for_catchup())
  File "/usr/local/lib/python3.7/site-packages/aiorpcX-0.18.7-py3.7.egg/aiorpcx/curio.py", line 255, in __aexit__
    await self.join()
  File "/usr/local/lib/python3.7/site-packages/aiorpcX-0.18.7-py3.7.egg/aiorpcx/curio.py", line 213, in join
    raise task.exception()
  File "/electrumx/electrumx/server/block_processor.py", line 702, in fetch_and_process_blocks
    await group.spawn(self._process_prefetched_blocks())
  File "/usr/local/lib/python3.7/site-packages/aiorpcX-0.18.7-py3.7.egg/aiorpcx/curio.py", line 255, in __aexit__
    await self.join()
  File "/usr/local/lib/python3.7/site-packages/aiorpcX-0.18.7-py3.7.egg/aiorpcx/curio.py", line 213, in join
    raise task.exception()
  File "/electrumx/electrumx/server/block_processor.py", line 663, in _process_prefetched_blocks
    await self.check_and_advance_blocks(blocks)
  File "/electrumx/electrumx/server/block_processor.py", line 230, in check_and_advance_blocks
    await self._maybe_flush()
  File "/electrumx/electrumx/server/block_processor.py", line 368, in _maybe_flush
    await self.flush(flush_arg)
  File "/electrumx/electrumx/server/block_processor.py", line 358, in flush
    await self.run_in_thread_with_lock(flush)
  File "/electrumx/electrumx/server/block_processor.py", line 212, in run_in_thread_with_lock
    return await asyncio.shield(run_in_thread_locked())
  File "/electrumx/electrumx/server/block_processor.py", line 211, in run_in_thread_locked
    return await run_in_thread(func, *args)
  File "/usr/local/lib/python3.7/site-packages/aiorpcX-0.18.7-py3.7.egg/aiorpcx/curio.py", line 68, in run_in_thread
    return await get_event_loop().run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/electrumx/electrumx/server/block_processor.py", line 357, in flush
    self.estimate_txs_remaining)
  File "/electrumx/electrumx/server/db.py", line 244, in flush_dbs
    self.flush_history()
  File "/electrumx/electrumx/server/db.py", line 313, in flush_history
    self.history.flush()
  File "/electrumx/electrumx/server/history.py", line 160, in flush
    flush_id = pack_be_uint16(self.flush_count)
struct.error: 'H' format requires 0 <= number <= 65535

**Comment by ecdsa** [comment] 2024-04-30 10:54
did you try to adjust FLUSH_COUNT_LIMIT in your settings? default is 65535

**Comment by thakurabu** [comment] 2024-04-30 11:01
version: "3.7"
services:
  electrs:
    container_name: electrs
    image: lukechilds/electrumx:latest
    volumes:
      - "../volumes/electrs:/data"
    ports:
      - "${APP_ELECTRS_PORT}:${APP_ELECTRS_PORT}"
      - 50002:50002
      - 8000:8000
      - 8080:8080
    healthcheck:
      test: "nc -z localhost 50001"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - DAEMON_URL=http://${APP_BITCOIN_RPC_USERNAME}:${APP_BITCOIN_RPC_PASSWORD}@${APP_BITCOIND_IP}:${APP_BITCOIND_RPC_PORT}
      - COIN=Bitcoin
      - SERVICES=tcp://:50001,ssl://:50002,wss://:50004,rpc://0.0.0.0:8000
      - REPORT_SERVICES=tcp://vmi204200.contaboserver.net:50001,tcp://vmi204200.contaboserver.net:8000,tcp://vmi204200.contaboserver.net:8080,ssl://vmi204200.contaboserver.net:5000>
      - NET=${APP_BITCOIN_NETWORK}
      - LOG_LEVEL=debug
      - DB_DIRECTORY=/data/db
      - FLUSH_COUNT=65535
      - OTHER_ENV_VARIABLE=value
    networks:
      default:
        ipv4_address: "${APP_ELECTRS_IP}"
this is my yml file

**Comment by thakurabu** [comment] 2024-04-30 11:04
Yes

**Comment by SomberNight** [comment] 2024-04-30 17:01
duplicate of https://github.com/spesmilo/electrumx/issues/88

> you should run the `electrumx_compact_history` script, while the server is stopped, using the same environment variables as otherwise

**Closed by SomberNight** 2024-04-30 17:01 UTC
