### ISSUE TITLE
Server crash soon after start on 'ill-formed response error object: no new valid entries'

### ISSUE THREAD

**Issue by whizz** [spesmilo/electrumx#27] opened 2020-06-22 19:59 UTC
Version 1.15.0, Ubuntu focal

Server starts up, but soon after crashes. On first look it seems like a problem with some peer. I'll investigate further. Here are the logs:

```
ERROR:electrumx:ElectrumX server terminated abnormally
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/EGG-INFO/scripts/electrumx_server", line 35, in main
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/lib/server_base.py", line 125, in run
    await server_task
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/lib/server_base.py", line 98, in serve
    await self.serve(shutdown_event)
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/server/controller.py", line 134, in serve
    await group.spawn(wait_for_catchup())
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/server/session.py", line 621, in serve
    await group.spawn(self._manage_servers())
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/server/peers.py", line 459, in discover_peers
    await group.spawn(self._import_peers())
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/server/peers.py", line 234, in _monitor_peer
    if await self._should_drop_peer(peer):
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/server/peers.py", line 277, in _should_drop_peer
    await self._verify_peer(session, peer)
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/server/peers.py", line 383, in _verify_peer
    await session.send_request('server.add_peer', [features])
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/session.py", line 529, in send_request
    return await self._send_concurrent(message, future, 1)
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/session.py", line 499, in _send_concurrent
    return await future
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/jsonrpc.py", line 721, in receive_message
    item, request_id = self._protocol.message_to_item(message)
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/jsonrpc.py", line 273, in message_to_item
    return cls._process_response(payload)
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/jsonrpc.py", line 220, in _process_response
    raise cls._error(code, message, False, request_id)
aiorpcx.jsonrpc.ProtocolError: (-32600, 'ill-formed response error object: no new valid entries')
```

**Comment by SomberNight** [comment] 2020-06-22 20:08
duplicate of https://github.com/spesmilo/electrumx/issues/22

**Closed by SomberNight** 2020-06-22 20:08 UTC

**Comment by calebadavis** [comment] 2020-06-27 15:03
I think this issue was closed in prematurely... I'm seeing this same crash repeatedly on my linux box (fedora 32) using the latest git 1.15 label, but there aren't two instances. Just the one. I have to re-start the server 3-4 times before it runs for a decent amount of time, but usually after a few hours, the same crash happens again. Same python traceback error as above.

**Comment by whizz** [comment] 2020-06-27 15:17
I think the fix is not in 1.15. You have to use master or wait for the next release. It fixed the issue for me.

**Comment by calebadavis** [comment] 2020-06-27 15:21
> I think the fix is not in 1.15. You have to use master or wait for the next release. It fixed the issue for me.

Ahh OK cool, I'll give master a whirl. Thanks!

**Comment by calebadavis** [comment] 2020-06-27 17:43
> I think the fix is not in 1.15. You have to use master or wait for the next release. It fixed the issue for me.

Ugh. Tried master but it didn't like my config file (COIN=BitcoinSegwit). Tried to set COIN=Bitcoin, but it still complained that Bitcoin+mainnet is a bad combo (I don't have a NET specified right now). What should I be using for BTC?

**Comment by whizz** [comment] 2020-06-27 17:49
That should work fine. Can you post your config?

I have
```
NET=mainnet
COIN=BitcoinSegwit
```

**Comment by calebadavis** [comment] 2020-06-27 18:06
Lightly scrubbed for security reasons: http://prowlers.com/~cdavis/electrumx.conf

**Comment by whizz** [comment] 2020-06-27 19:33
That is weird. Could you also post the logs for the startup sequence? Could it be possible that your config is not being used?

**Comment by calebadavis** [comment] 2020-06-27 20:16
> That is weird. Could you also post the logs for the startup sequence? Could it be possible that your config is not being used?

It was my mistake. I stupidly built from the kyuupichan repo (old habits die hard) this morning. My server seems to be running normally again. Thanks again for your help.
